/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "places.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

placesRet *
airports_near_city_1(clientArg *argp, CLIENT *clnt)
{
	static placesRet clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, AIRPORTS_NEAR_CITY,
		(xdrproc_t) xdr_clientArg, (caddr_t) argp,
		(xdrproc_t) xdr_placesRet, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
